import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import AppThemeProvider from "@/context/AppThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <SessionProvider>
          <AppThemeProvider>
            {children}
          </AppThemeProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
